### ISSUE TITLE
BanHammer not following PEX hierarchy

### ISSUE THREAD

**Issue by CyanLights** [grandwazir/BanHammer#23]
Hello,

I am not certain if this was an intended feature (or lack thereof) or if I am just completely missing something. However, it has come to my attention that my MODs (lowest ranked staff) can ban or kick Owners (highest rank). Is there a way to only let MODs ban Members, and so on and so forth?

Thank you kindly.

Current Build:
- Craftbukkit 2149
- Essentials 2.9.200 Dev
- PermissionsEX 1.9.2
- WorldEdit 5.3
- WorldGuard 5.5.2
- LogBlock 1.5.2
- LWC 4.1.1 (b645)/4.1.1
- mcMMO 1.3.05
- Citizens 1.2
- Iconomy 6.0.10b
- Vault
- Backup
- AutoShutdown 2.2
- BanHammer 1.9.1
- VoxelSniper 1.1.2

**Comment by grandwazir** [comment]
BanHammer does not have any bias towards any permission systems, meaning it only uses features that are common to SuperPerms and as such does not support PEX's hierarchy system.

Once upon a time BanHammer did support a system which gave a player's actions a certain amount of weight. A heavier player could ban lighter players. That said, the system fell down because it could not check the weight of offline players. This is because the current Bukkit permission system does not allow attaching permissions to players who are offline.

The two options available for implementing this are either a basic list of people who can not be banned (could not be a permission node for the reasons above) or waiting until we can check the permission of offline players. See the other issue - grant immunity to some players for more details.
