### ISSUE TITLE
Pardoning a player erases old Database entries. 

### ISSUE THREAD

**Issue by JoneKone** [grandwazir/BanHammer#6]
Currently when I /pardon aplayer

it will purge old entryes from the database.. So if I reban a person.. "first ban few days" warning ban.. then pardon while he is still banned and reban instantly permanently.

After that when I check the /bh history on mr aplayer It will only give me the permanently ban entry. Not the old 7 days ban..

Allso a feature where this pardon that I do could be automatic.

If a person is under 7 days warning ban and then op finds more grief and wants to perm ban him. He must pardon first then reban without "t:" parameter.

There could be an option in config to enable an option to allow ppl rebanning while ppl is still banned.. "more time could be added, it would just add time to the old ban and maby make a nother mark to database (added time etc.)"

for example X is banned for 7 days and after 2 days OP finds more grief of X OP could just "/ban X reason t:8" <- and it would add time to old ban and make new Database Entry normal entry or a custom message added time for X's ban 8 days.

X is banned for 13 days and after 4 days OP find even MORE grief and desides to Perm ban X. "/ban X reason" and another entry perm ban is activated that either erases old Database entry's time table entry. Or if config isn't set right it will erase old entries and replace them with a new perm ban..

JoneK

**Comment by grandwazir** [comment]
This is currently by design. When you pardon a player I imagined that you would want to clear any record of that ban; for example if you made a ban by mistake.

Time being added would be something I would consider adding although I do not currently have a time frame to adding it to the plugin.

**Comment by fromgate** [comment]
I'm voting for this feature too.
Sometimes we unbanning people before ban period. But we need to save ban-history.

**Comment by ryans1230** [comment]
I was thinking of something along the same lines also. My idea was when looking up the history of a player it would return with another line called "Status:". It would have three options; "Banned.", "Expired." or "Pardoned by USERNAME reason:MESSAGE." You would have to modify the pardon action to allow for a reason to be given (but can be left empty).

For example: Notch discovers that Griefer1994 destroyed an entire building. When Griefer1994's history is pulled up, Notch only sees that he was banned for spamming chat a few months back. What Notch does not know (commonly a problem on large servers) is that Griefer1994 was perm. banned two other times for griefing, but was pardoned because his account was hacked or whatever.

Essentially it is changing how /pardon player changes the history and all bans are kept on record, regardless of status (purging would still be allowed).
