### ISSUE TITLE
add permissions

### ISSUE THREAD

**Issue by jaboy** [grandwazir/BanHammer#61]
Hey

Could you add a permission to bypass the "immune-players" players from the config ?

Right now the bypass its a part of the permission called "banhammer", but i need to have a more specific permission so i can deny it

**Comment by grandwazir** [comment]
That sounds like a sensible idea. How about if you have `banhammer.ban` instead?

This would make sense since giving someone a root permission of command should allow them to everything with the command.

Alternatively I could add `banhammer.ban.immune` and set it so you do not get that automatically when you assign `banhammer.ban`.

**Comment by jaboy** [comment]
it could also be banhammer.immune or banhammer.override, that way you can still give banhammer.\* in permissions
