### ISSUE TITLE
Error for 1.6

### ISSUE THREAD

**Issue by ArtificialTruth** [grandwazir/BanHammer#72]
http://pastebin.com/mAyupwjY
This is the version:
http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.2.6-SNAPSHOT/

**Comment by grandwazir** [comment]
I believe this is now fixed in the latest version and so I will now close this issue. Please try the latest development version of BanHammer (available [here](http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.3.0-SNAPSHOT/)) and see if that fixes it. If it happens again reopen this issue and I can look at it further.
