### ISSUE TITLE
Error in messages for kick and pardon

### ISSUE THREAD

**Issue by jaboy** [grandwazir/BanHammer#77]
Hello

I have made so everyone can see when i kick / ban from the server
But whenever i kick someone off the the server, instead of everyone getting the message that the player has been kicked, the kicker gets all the messages
(see screen shot) and the rest cant see he get kicked
![2013-07-28_15 20 29](https://f.cloud.github.com/assets/916338/868274/d2055102-f78a-11e2-9a70-18ee5851c216.png)

when you pardon a player you get the "player has been pardoned" message twice

Plugin version: BanHammer v2.2.6-SNAPSHOT
(is reported by the plugin on startup)

**Comment by grandwazir** [comment]
I think both bugs are now fixed in the latest development version. Please try it [here](http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.3.0-SNAPSHOT/). Bear in mind it is a beta so always backup your database first. 

I am going to close this issue as I think it is resolved. Please reopen it if you get the same bug on the development version.
