### ISSUE TITLE
Error with bh import

### ISSUE THREAD

**Issue by lorenzreweghs** [grandwazir/BanHammer#80]
I tried to do /bh import (with here of course a reason) but this error appeared:
http://pastebin.com/UtxmMGje
Because of this, I can't use your plugin.

Greetz,
Crossfire

**Comment by grandwazir** [comment]
Please try the same with the latest development snapshot available [here](http://repository.james.richardson.name/snapshots/name/richardson/james/bukkit/ban-hammer/2.3.0-SNAPSHOT/) and see if the problem persists.

**Comment by lorenzreweghs** [comment]
Now, this error appeared:
http://pastebin.com/s9rApmYe
My server even crashed too.

**Comment by grandwazir** [comment]
This appeared to happen because the plugin attempted to create the cache at the same time you were adding records to the database. Wait about 1 minute after the server has started, then try using the command.

Additionally please turn on debugging by changing the LOGGING value in config.yml to ALL. This will help me debug your issue.

**Comment by grandwazir** [comment]
Caching has been disabled now due to a long standing bug in the out of date library that bukkit ships. As such this is no longer an issue.
