### ISSUE TITLE
Umlauts and other special characters removed from kick & ban reason

### ISSUE THREAD

**Issue by ayyy** [grandwazir/BanHammer#90]
Hey.

If you enter special characters(tried: ,.-+¨'), umlauts (äåö), as a ban or kick reason, those characters are removed from the reason.

And a message from my fellow admins: You have 10 minutes to fix this issue or we're switching to a competing plugin.

**Comment by grandwazir** [comment]
Incredible. Who exactly do your fellow administrators think they are to make demands from me and issue ultimatums. It shows an extraordinary amount of ignorance of their part of how open source software works.

If you issue an apology for your inappropriate and rude behaviour I may consider looking at this issue for you. Otherwise the source is available, fix it yourself.

**Comment by ayyy** [comment]
Oh, that was supposed to be taken as a joke. Sorry. :S

**Comment by grandwazir** [comment]
Apology accepted. I will look at this when time allows. Are you using MySQL or SQLite?

**Comment by grandwazir** [comment]
OK. When I get time I will see if I can duplicate the issue.

**Comment by ayyy** [comment]
Awesome, thanks. Aaand, I accidently deleted my comment. God this day isn't going well.

**Comment by grandwazir** [comment]
I am pretty sure this is down to the default character setting for your database table. Check what setting it is for you and change it to UTF-8 if you want to use these characters.

**Comment by Mr-Rixa** [comment]
@grandwazir, "collation: utf8_general_ci" https://db.tt/x8MyFaVH Diaeresis letters (Ä,Ö,Å), commas, dots, etc not showing on reasons, they did before. 

Actually I checked, BH doesn't save these even on MySQL anymore, but it did before. I can browse through the bans and try to find where it broke, but I'm not promising anything.

Oh yeah, [INFO] BanHammer (2.3.1)

```
>bh ban testitesti t:grief tämä on testi, jossa on pilkku ja ääkkösiä.
11:38:45 [INFO] You have banned testitesti.
11:38:45 [INFO] testitesti has been banned by CONSOLE.
11:38:45 [INFO] - Reason: t m on testi jossa on pilkku ja kk si 
11:38:45 [INFO] - Length: 4 months 1 month 2 days 4 hours 25 minutes 19 seconds 150 milliseconds.
```

ban reason translated is "This is a test, which has a comma and diaeresis."

**Comment by remiscarlet** [comment]
Tested with both MySQL and without, I would assume the banhammer.db is properly set up with encodings but MySQL is definitely set to UTF-8 and symbols still fail to show up in ban/kick reasons. Anything I can do to provide more information on the issue?

edit: After a friend of mine looked through the code, he mentioned this. 

```
https://github.com/grandwazir/BukkitUtilities/blob/master/src/main/java/name/richardson/james/bukkit/utilities/command/context/AbstractCommandContext.java

specifically the argument matcher which matches for words only, which would ignore punctuation
```

He had to go for the night so I can't get anything else but perhaps it might be worth looking into.

edit2: Another thing he pointed out

```
Oh this is the punctuation and the Unicode problem. \w in java doesn't match Unicode see: 
http://stackoverflow.com/questions/4304928/unicode-equivalents-for-w-and-b-in-java-regular-expressions
```

Thanks for your work on this plugin! It's definitely made life a lot easier on me and my server staff!

**Comment by grandwazir** [comment]
The argument matcher might be what is striping it out. Thanks for digging this out. I will look at it closer tomorrow.

**Comment by remiscarlet** [comment]
Np! Thanks again for your work!

**Comment by msm595** [comment]
Bump

**Comment by davidlohle** [comment]
Definitely, bump. Our ban messages looked like butchered English as a result. A fix would be GREATLY appreciated.

There aren't many different features between the current version of BH and version 1.9. With some simple MySQL commands, you can revert back to the old schema and just use the old BanHammer and get the unchanged ban messages. It's a pretty easy task if it's something that really matters while we wait for the fix. (We just recently updated to the most recent version after using 1.9.x since it first came out)

**Comment by grandwazir** [comment]
This has been fixed upstream in BukkitUtilities. When I next release BanHammer it will have this appropriate fix.

@Proplex 1.9 is also around 2 years old and I wouldn't recommend (and definitely don't support) altering the database schema manually. If you choose to do that and you break it, you get to keep both pieces.

**Comment by davidlohle** [comment]
@grandwazir We reverted back to 1.9 and it's been smooth sailing since. We had used 1.9 this entire time but only recently had we upgraded. I reverted from a backup dump I made prior to and then it was just a matter of re-banning the few players we missed in the interim. I'll update once everything is fixed. As an English teacher, I go crazy as a result of the broken grammar.

**Comment by grandwazir** [comment]
This is now fixed in the latest snapshot that was shipped a couple of weeks ago. There should be no more problems with butchered characters, let me know if you find any.
